plugins {
    id 'java-library'
}

group = 'org.kyouroga'
version = '1.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    implementation project(':common')
    implementation project(':universal')
    implementation 'org.yaml:snakeyaml:2.0'
    compileOnly 'com.velocitypowered:velocity-api:3.4.0'
}
